DVC Stages creation
trujillo9616/mlops-bootcamp-e7 pull request #7
Opened 2024-09-01 05:42 UTC by ricardo8a

#### What does this PR do?
creates dvc stages
data_prepare
featurize
elbow
train
#### How should this be manually tested?
run command
dvc repro
#### Any background context you want to provide?
verify exists csv.
#### What are the relevant tickets?

#### Screenshots
the command create images in the doc directory

#### Type of change

- [x] New feature (non-breaking change which adds functionality)

#### Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective, or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2024-09-02 06:23 UTC, trujillo9616 requested changes
Is there a reason the `dvc.lock` file was no included?

2024-09-02 06:23 UTC, trujillo9616 commented on data/raw/online_retail_raw.csv
@ricardo8a Can we remove this file? We're tracking the data files with DVC so uploading the dataset to our repo is not a good practice.

2024-09-02 23:44 UTC, ricardo8a commented on data/raw/online_retail_raw.csv
yes, I will remove that file

2024-09-02 23:45 UTC, ricardo8a commented on data/raw/online_retail_raw.csv
I added because I cannot download from aws s3

2024-09-05 07:52 UTC, trujillo9616 approved these changes
🚀

2024-09-05 16:31 UTC, merged